In [5]:
import numpy as np
from numpy.linalg import inv
A = np.array([[4,0],[0,2],[1,1]])
b = np.array([[2],[0],[11]])
print(A)
print(b)
At = A.T
print(At)

X = inv(At@A)@At@b

print(X)

[[4 0]
 [0 2]
 [1 1]]
[[ 2]
 [ 0]
 [11]]
[[4 0 1]
 [0 2 1]]
[[1.]
 [2.]]


In [6]:
from numpy.linalg import pinv
x = pinv(A)@b
print(x)

[[1.]
 [2.]]


In [15]:
from numpy.linalg import norm
err = norm(A@x-b)
print(err)

9.16515138991168
