In [3]:
import numpy as  np 
from numpy import linalg as LA


## eigen vectors

In [5]:
A = np.array([[1,1,-1,0],[0,5,0,-1],[-1,-3,2,0],[-2,2,0,3]])
Lambda = 3


## eigen Pairs


In [7]:
A = np.array([[11,-20],[4,-7]])
Lambda = 3
u = np.array([[4],[1],[-7],[0]])

eigen_value = Lambda * u

#print(A@u)

print(eigen_value)

NameError: name 'u' is not defined

In [10]:
A = np.array([[3,0,-1],[2,3,1],[-3,4,5]])
print(A)

l, ev = LA.eig(A)
print('Eigen values are:', l )
print('eigen vectors are:', ev[:,0],'and',ev[:,1])

[[ 3  0 -1]
 [ 2  3  1]
 [-3  4  5]]
Eigen values are: [0.62771868 4.         6.37228132]
eigen vectors are: [ 0.3158391  -0.58211367  0.74925919] and [-0.57735027 -0.57735027  0.57735027]
