In [41]:
import numpy as np
from numpy.linalg import inv 
from numpy.linalg import norm
A = np.array([[1,2],[-3,-5]])
Ainv = inv(A)
print(A)
print(inv(A))



[[ 1  2]
 [-3 -5]]
[[-5. -2.]
 [ 3.  1.]]
[[1.00000000e+00 2.22044605e-16]
 [1.11022302e-16 1.00000000e+00]]
