# Application: Least-squares approximation

### THE GENREAL LEAST-SQUARES PROBLEM

In [7]:
import numpy as np
from numpy.linalg import inv
A = np.array([[6,7],[-1,-1]])
b = np.array([[-3],[1]])

print(A)
print(b)

x = inv(A.T@A)@A.T@b
print(x)

[[ 6  7]
 [-1 -1]]
[[-3]
 [ 1]]
[[-4.]
 [ 3.]]


### OR 

In [11]:
from numpy.linalg as pinv
x = pinv(A)@b
print(x)

err = norm(A@x - b)
print(err)

[[-4.]
 [ 3.]]


NameError: name 'norm' is not defined

## Finding a least-squares solution.


In [40]:
import numpy as np
import sympy
from numpy.linalg import inv
import matplotlib.pyplot as plt
A = np.array([[1,12],[1,20],[1,22],[1,6]])
b = np.array([[307],[445.6],[485.2],[184.6]])

print('Matrix A',A)
print('Matrix B',b)

ATA = A.T @ A
ATb = A.T @ b 

print('ATA = ',ATA)
print('ATb = ',ATb)

#ATA = np.array([[4,48],[48,774]])
#ATb = np.array([[491.5],[6898.0]])

# Create an augmented matrix
augmented_matrix = np.hstack((ATA, ATb))

# Find the reduced row echelon form
rref = sympy.Matrix(augmented_matrix).rref()[0]

# Extract the solution from the reduced row echelon form
solution = rref[:, -1]

print("Solution:", solution)




Matrix A [[ 1 12]
 [ 1 20]
 [ 1 22]
 [ 1  6]]
Matrix B [[307. ]
 [445.6]
 [485.2]
 [184.6]]
ATA =  [[   4   60]
 [  60 1064]]
ATb =  [[ 1422.4]
 [24378. ]]
Solution: Matrix([[77.3682926829268], [18.5487804878049]])


## Finding a least-squares approximation to a quadratic.