In [1]:
import numpy as np 
from numpy import linalg


In [2]:
X = np.array([[0.27,-0.35,-0.51],[39.05,19.64,48.5]])
print(X)
X.shape

[[ 0.27 -0.35 -0.51]
 [39.05 19.64 48.5 ]]


(2, 3)

In [3]:
m = X.mean(axis = 1)
print(m)
B = X - m.reshape(2,1)
B

[-0.19666667 35.73      ]


array([[  0.46666667,  -0.15333333,  -0.31333333],
       [  3.32      , -16.09      ,  12.77      ]])

In [16]:
S = (B@B.T)/(X.shape[1]-1)
S

array([[1.69733333e-01, 7.60000000e-03],
       [7.60000000e-03, 2.16491700e+02]])

In [18]:
S.trace()

216.66143333333332

In [22]:
tv =  np.var(S)
tv

8782.873558911875

In [5]:

l,p = linalg.eig(S)
print(l)
print(p)
D= p.T @S
D


[1.69733066e-01 2.16491700e+02]
[[-9.99999999e-01 -3.51328166e-05]
 [ 3.51328166e-05 -9.99999999e-01]]


array([[-1.69733066e-01,  5.96320069e-06],
       [-7.60596321e-03, -2.16491700e+02]])

In [6]:
p = np.array([[-0.96,0.26],[0.26,0.96]])
x = np.array([[8,9,11],[30,34,41]])
y = p @ X
print(p)
print(x)
y

[[-0.96  0.26]
 [ 0.26  0.96]]
[[ 8  9 11]
 [30 34 41]]


array([[ 9.8938,  5.4424, 13.0996],
       [37.5582, 18.7634, 46.4274]])

In [7]:
Y = p.T @ B
Y 


array([[  0.4152    ,  -4.0362    ,   3.621     ],
       [  3.30853333, -15.48626667,  12.17773333]])