### The Diagonalization Theorem
An nxn matrix A is diagonalizable if and only if A has n
linearly independent eigenvectors.

If the above holds, we can write A=PDP-1 where D is a
diagonal matrix. The diagonal entries of D are
eigenvalues of A that correspond, respectively, to the
eigenvectors in P.

In [3]:
import numpy as np 
from numpy import linalg
A = np.array([[1,0],[6,-1]])
A

array([[ 1,  0],
       [ 6, -1]])

In [5]:
detA = linalg.det(A)
detA

-1.0

First find the eigen value and eigen vectors 

In [7]:
l , ev  = linalg.eig(A)
l

array([-1.,  1.])

In [9]:
ev

array([[0.        , 0.31622777],
       [1.        , 0.9486833 ]])

We are reducing it to the echelon form just to check if it is dependent or independent

In [107]:
import sympy as sp 
rref_M, pivot_cols = sp.Matrix(ev).rref()
rref_M

Matrix([
[1, 0],
[0, 1]])

In [25]:
pivot_cols

(0, 1, 2)

If when reduced into a echelon form if it has a coloumn of zeros then we can say thats its not linearly independent 

Now, that we know that eigenvectors are linearly independent we know, we can
diagonalize the matrix A. Let’s form D and P.

Pivot voloumns

In [11]:
D = np.diag(l)
D

array([[-1.,  0.],
       [ 0.,  1.]])

The main diagonal 1, -2 , - 2 are the iegen values 

In [13]:
P = abs(ev)
P

array([[0.        , 0.31622777],
       [1.        , 0.9486833 ]])

The eigen values D should be corresponding to the eigen vector P 

In [15]:
ev = np.array([[3,2],[1,1]])
P_inv = linalg.inv(ev)
print(ev)
P_inv

[[3 2]
 [1 1]]


array([[ 1., -2.],
       [-1.,  3.]])

In [17]:
P@D@P_inv

array([[-0.31622777,  0.9486833 ],
       [-1.9486833 ,  4.84604989]])

### B =M^-1 AM

In [49]:
A = np.array([[-3,-2,0,0],[-3,4,0,0],[0,0,-5,-4],[0,0,-2,2]])
M = np.array([[0,0,1,2],[0,0,3,1],[4,-1,0,0],[1,2,0,0]])
M_inv = linalg.inv(M)
B = abs(M_inv@A@M)
B

array([[6.00000000e+00, 2.22044605e-16, 0.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 3.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.40000000e+00, 8.00000000e-01],
       [0.00000000e+00, 0.00000000e+00, 7.20000000e+00, 4.40000000e+00]])

In [137]:
p = np.array([[3,1],[2,1]])
D = np.array([[4,-3],[2,-1]])
p_inv = linalg.inv(p)

A = p_inv@D@p
A

array([[2.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.00000000e+00]])

### Principal Component Analysis