In [198]:
import numpy as np
import pandas as pd
from numpy import linalg as la 

In [199]:
A = np.array([[6,-3,-3,0],[0,-3,-3,6]])
A

array([[ 6, -3, -3,  0],
       [ 0, -3, -3,  6]])

In [200]:
result = np.dot(A.T, A)
result

array([[ 36, -18, -18,   0],
       [-18,  18,  18, -18],
       [-18,  18,  18, -18],
       [  0, -18, -18,  36]])

In [201]:
l, ev = la.eig(result)
print(l)
print(ev)

[7.10542736e-15 3.60000000e+01 7.20000000e+01 0.00000000e+00]
[[ 5.00000000e-01  7.07106781e-01 -5.00000000e-01  3.12807954e-02]
 [ 5.00000000e-01 -1.55901856e-16  5.00000000e-01  7.37002429e-01]
 [ 5.00000000e-01 -3.05195810e-16  5.00000000e-01 -6.74440838e-01]
 [ 5.00000000e-01 -7.07106781e-01 -5.00000000e-01  3.12807954e-02]]


### SVD code

In [203]:

U,S,VT = np.linalg.svd(A)

print("U:")
print(U)
print(U.shape)

print("S:")
print(S)
print(S.shape)

print("VT:")
print(VT.T)
print(VT.shape)

U:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
(2, 2)
S:
[8.48528137 6.        ]
(2,)
VT:
[[-5.00000000e-01 -7.07106781e-01  2.26209191e-01  4.45902906e-01]
 [ 5.00000000e-01  1.81592985e-16 -4.04392746e-01  7.65811012e-01]
 [ 5.00000000e-01  1.36268319e-16  8.56811129e-01  1.25994800e-01]
 [-5.00000000e-01  7.07106781e-01  2.26209191e-01  4.45902906e-01]]
(4, 4)
