vector operations

In [34]:
import numpy as np 
u = np.array([[5],[-9],[2]])
print(u.shape)

v = np.array([[8],[-5],[-6]])
k = np.array([[9],[1],[7]])

print(5*u+4*v+3*k)


(3, 1)
[[ 84]
 [-62]
 [  7]]


Matrix Multiplication

In [15]:
import numpy as np
A = np.array([[-5,3,-4],[-5,2,-1],[5,-1,3]])
B = np.array([[3],[2],[-1]])

print('A=\n' ,A, '\n' , 'B=\n',B) 

print(A@B)

A=
 [[-5  3 -4]
 [-5  2 -1]
 [ 5 -1  3]] 
 B=
 [[ 3]
 [ 2]
 [-1]]
[[ -5]
 [-10]
 [ 10]]


In [26]:
import numpy as np
A = np.array([[1,2,3],[1,0,1],[4,1,2],[2,3,0],[5,2,4],[0,2,5]])
B = np.array([[2,1,2],[1,3,0],[2,0,5]])

AT = A.T
BT = B.T

print('A=\n' ,A, '\n' , 'B=\n',B) 
print('A_Transpose=\n',AT)
print('B_Transpose=\n',BT)
print('shapes of A and B matrix',A.shape,B.shape)
print('shapes of A and B matrix',AT.shape,BT.shape)

Products = [    (A, A), (A, AT), (A, B), (A, BT),
    (AT, A), (AT, AT), (AT, B), (AT, BT),
    (B, A), (B, AT), (B, B), (B, BT),
    (BT, A), (BT, AT), (BT, B), (BT, BT)
]
for i , j in 




A=
 [[1 2 3]
 [1 0 1]
 [4 1 2]
 [2 3 0]
 [5 2 4]
 [0 2 5]] 
 B=
 [[2 1 2]
 [1 3 0]
 [2 0 5]]
A_Transpose=
 [[1 1 4 2 5 0]
 [2 0 1 3 2 2]
 [3 1 2 0 4 5]]
B_Transpose=
 [[2 1 2]
 [1 3 0]
 [2 0 5]]
shapes of A and B matrix (6, 3) (3, 3)
shapes of A and B matrix (3, 6) (3, 3)


Dot Product

In [43]:
import numpy as np 
from numpy.linalg import norm 
u = np.array([5,-5,6])
v = np.array([-2,-7,-1])
print(np.dot(u,v))


19


lenght of the vector

In [5]:
import math 
u = [1,-3,4]
math.sqrt(np.dot(u,u))

5.0990195135927845

In [6]:
from numpy.linalg import norm 
norm(u)

5.0990195135927845

Unit Vector

In [7]:
a = np.array([1,-2,2,0])
unitA = a/norm(a)
print(unitA)
norm(a)

[ 0.33333333 -0.66666667  0.66666667  0.        ]


3.0

Find the angle between the vectors

In [38]:
import numpy as np 
import math
from numpy.linalg import norm 
u = np.array([-2,9,5]) ##enter the first matrix
v = np.array([-6,-9,4]) ## enter the second matrix
dot= np.dot(u,v)
mag_u = norm(u)
mag_v = norm(v)

costheta = dot / (mag_u * mag_v)

rad = math.acos(costheta)
deg = math.degrees(rad)

print(deg)


113.89807621333344


scalar projection of vector

In [58]:
import numpy as np
from numpy.linalg import norm 
u = np.array([-6,9,-5])
v = np.array([-2,7,1])
dot = np.dot(u,v)
mag_v = norm(v)

comp_V_on_U = dot/ mag_v
print(comp_V_on_U )



9.525793444156804


Vector Projection

In [60]:
import numpy as np
from numpy.linalg import norm
u = np.array([8,-5,-6])
v = np.array([9,4,-4])
dot = np.dot(u,v)
mag_v = norm(v)

proj_V = (dot / mag_v**2)*v
print(proj_V)

[ 6.05309735  2.69026549 -2.69026549]


Matrix addition and subtraction 

In [89]:
import numpy as np
u = np.array([[5,0],[-6,-8]])
v = np.array([[-3,4],[3,-5]])
print(u.shape)
print(v.shape)
print('v=\n' ,u, '\n' , 'v=\n',v) 
u+v


(2, 2)
(2, 2)
v=
 [[ 5  0]
 [-6 -8]] 
 v=
 [[-3  4]
 [ 3 -5]]


array([[  2,   4],
       [ -3, -13]])

matrix multiplication

In [86]:
import numpy as np 
u = np.array([[8,-9],[0,2]])
##v = np.array([[3,0,0],[0,9,0],[0,0,8]])
print(u.shape)
print(v.shape)

print('v=\n' ,u, '\n' , 'v=\n',v) 

u**3


(2, 2)
(3, 3)
v=
 [[3 0]
 [0 2]] 
 v=
 [[3 0 0]
 [0 9 0]
 [0 0 8]]


array([[27,  0],
       [ 0,  8]])

In [7]:
import pandas as pd

# Example data
A = [[1, 2, 3], [4, 5, 6]]
B = [[7, 8, 9], [10, 11, 12]]

# Create DataFrames
df1 = pd.DataFrame(A, columns=['Action', 'Drama', 'Documentary'])
df2 = pd.DataFrame(B, columns=['The Batman', 'Mickey 17', 'Bowling for Columbine'])

# Use the Styler object to hide the index
df1_styled = df1.style.hide(axis='index')

# To view the styled DataFrame in Jupyter Notebook or similar environment
df1_styled


In [1]:
import numpy as np

A = np.array([[1, 2, 3],
              [1, 0, 1],
              [4, 1, 2],
              [2, 3, 0],
              [5, 2, 4],
              [0, 2, 5]])

B = np.array([[2, 1, 2],
              [1, 3, 0],
              [2, 0, 5]])

# Transpose of matrix A
AT = A.T

# Transpose of Matrix B
BT = B.T

# Print the matrices
print("A:\n", A)
print("B:\n", B)
print("AT:\n", AT)
print("BT:\n", BT)

# Perform all possible matrix multiplications and check compatibility
products = [
    ("A * A", A, A), ("A * AT", A, AT), ("A * B", A, B), ("A * BT", A, BT),
    ("AT * A", AT, A), ("AT * AT", AT, AT), ("AT * B", AT, B), ("AT * BT", AT, BT),
    ("B * A", B, A), ("B * AT", B, AT), ("B * B", B, B), ("B * BT", B, BT),
    ("BT * A", BT, A), ("BT * AT", BT, AT), ("BT * B", BT, B), ("BT * BT", BT, BT)
]

for name, matrix1, matrix2 in products:
    try:
        result = np.dot(matrix1, matrix2)
        print(f"{name}:")
        print(f"{matrix1.shape} @ {matrix2.shape} = {result.shape}")
        print(result)
    except ValueError:
        print(f"{name}: Incompatible")

A:
 [[1 2 3]
 [1 0 1]
 [4 1 2]
 [2 3 0]
 [5 2 4]
 [0 2 5]]
B:
 [[2 1 2]
 [1 3 0]
 [2 0 5]]
AT:
 [[1 1 4 2 5 0]
 [2 0 1 3 2 2]
 [3 1 2 0 4 5]]
BT:
 [[2 1 2]
 [1 3 0]
 [2 0 5]]
A * A: Incompatible
A * AT:
(6, 3) @ (3, 6) = (6, 6)
[[14  4 12  8 21 19]
 [ 4  2  6  2  9  5]
 [12  6 21 11 30 12]
 [ 8  2 11 13 16  6]
 [21  9 30 16 45 24]
 [19  5 12  6 24 29]]
A * B:
(6, 3) @ (3, 3) = (6, 3)
[[10  7 17]
 [ 4  1  7]
 [13  7 18]
 [ 7 11  4]
 [20 11 30]
 [12  6 25]]
A * BT:
(6, 3) @ (3, 3) = (6, 3)
[[10  7 17]
 [ 4  1  7]
 [13  7 18]
 [ 7 11  4]
 [20 11 30]
 [12  6 25]]
AT * A:
(3, 6) @ (6, 3) = (3, 3)
[[47 22 32]
 [22 22 26]
 [32 26 55]]
AT * AT: Incompatible
AT * B: Incompatible
AT * BT: Incompatible
B * A: Incompatible
B * AT:
(3, 3) @ (3, 6) = (3, 6)
[[10  4 13  7 20 12]
 [ 7  1  7 11 11  6]
 [17  7 18  4 30 25]]
B * B:
(3, 3) @ (3, 3) = (3, 3)
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]
B * BT:
(3, 3) @ (3, 3) = (3, 3)
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]
BT * A: Incompatible
BT * AT:
(3, 3) @ (3, 

In [2]:
A@B


array([[10,  7, 17],
       [ 4,  1,  7],
       [13,  7, 18],
       [ 7, 11,  4],
       [20, 11, 30],
       [12,  6, 25]])

In [3]:
A@AT

array([[14,  4, 12,  8, 21, 19],
       [ 4,  2,  6,  2,  9,  5],
       [12,  6, 21, 11, 30, 12],
       [ 8,  2, 11, 13, 16,  6],
       [21,  9, 30, 16, 45, 24],
       [19,  5, 12,  6, 24, 29]])

In [5]:
import numpy as np

A = np.array([[1, 2, 3],
              [1, 0, 1],
              [4, 1, 2],
              [2, 3, 0],
              [5, 2, 4],
              [0, 2, 5]])

B = np.array([[2, 1, 2],
              [1, 3, 0],
              [2, 0, 5]])

# Transpose of matrix A
AT = A.T

# Transpose of Matrix B
BT = B.T
products = [
    (A, A), (A, AT), (A, B), (A, BT),
    (AT, A), ( AT, AT), (AT, B), (AT, BT),
    (B, A), (B, AT), (B, B), (B, BT),
    (BT, A), (BT, AT), (BT, B), (BT, BT)
]
i = 0
while i <len(products):
    matrix1 , matrix2 = products[i]
    try:
        result = np.dot(matrix1,matrix2)
        print(f"{matrix1.shape} @ {matrix2.shape} = {result.shape}")
        print(result)
    except ValueError:
        print(f"{matrix1.shape} @ {matrix2.shape} is incompatible")
    i+=1
    

(6, 3) @ (6, 3) is incompatible
(6, 3) @ (3, 6) = (6, 6)
[[14  4 12  8 21 19]
 [ 4  2  6  2  9  5]
 [12  6 21 11 30 12]
 [ 8  2 11 13 16  6]
 [21  9 30 16 45 24]
 [19  5 12  6 24 29]]
(6, 3) @ (3, 3) = (6, 3)
[[10  7 17]
 [ 4  1  7]
 [13  7 18]
 [ 7 11  4]
 [20 11 30]
 [12  6 25]]
(6, 3) @ (3, 3) = (6, 3)
[[10  7 17]
 [ 4  1  7]
 [13  7 18]
 [ 7 11  4]
 [20 11 30]
 [12  6 25]]
(3, 6) @ (6, 3) = (3, 3)
[[47 22 32]
 [22 22 26]
 [32 26 55]]
(3, 6) @ (3, 6) is incompatible
(3, 6) @ (3, 3) is incompatible
(3, 6) @ (3, 3) is incompatible
(3, 3) @ (6, 3) is incompatible
(3, 3) @ (3, 6) = (3, 6)
[[10  4 13  7 20 12]
 [ 7  1  7 11 11  6]
 [17  7 18  4 30 25]]
(3, 3) @ (3, 3) = (3, 3)
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]
(3, 3) @ (3, 3) = (3, 3)
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]
(3, 3) @ (6, 3) is incompatible
(3, 3) @ (3, 6) = (3, 6)
[[10  4 13  7 20 12]
 [ 7  1  7 11 11  6]
 [17  7 18  4 30 25]]
(3, 3) @ (3, 3) = (3, 3)
[[ 9  5 14]
 [ 5 10  2]
 [14  2 29]]
(3, 3) @ (3, 3) = (3, 3)
[[ 9  5 1

In [30]:
import numpy as np
from numpy.linalg import inv
A = np.array([[-1,-7],[1,6]])
print(A)
print(inv(A))


[[-1 -7]
 [ 1  6]]
[[ 6.  7.]
 [-1. -1.]]


## X = A^-1b

In [32]:
import numpy as np
from numpy.linalg import inv
A = np.array([[6,7],[-1,-1]])
b = np.array([[-3],[1]])
print(A)
x = A@b
print(x)

[[ 6  7]
 [-1 -1]]
[[-11]
 [  2]]


 ## Balancing a chemical equation 

In [ ]:
import numpy as np
from numpy.linalg import inv
A = np.array([[6,7],[-1,-1]])
b = np.array([[-3],[1]])
Ainv =inv(A)
print(Ainv)
x = A@b
print(x)