## Assignment 2 Cosine Similarity

#### Importing numpy, Pandas and random

In [3]:
import numpy as np
import pandas as pd
import random

df = pd.read_csv("senate_votes.csv")
df.head()

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
0      Akaka     D    HI  -1  -1   1   1   1  -1  -1  ...    1   -1   -1    1   
1  Alexander     R    TN   1   1   1   1   1   1   1  ...    1    1    1    1   
2     Allard     R    CO   1   1   1   1   1   1   1  ...    1    1    1    1   
3      Allen     R    VA   1   1   1   1   1   1   1  ...    1    1    1    1   
4     Baucus     D    MT  -1   1   1   1   1   1  -1  ...    1   -1    1    0   

   B41  B42  B43  B44  B45  B46  
0   -1    1   -1    1    1   -1  
1    1    1    1    0    1    1  
2    1    1    1    1    1    1  
3    1    1    1    1    1    1  
4    1    1   -1    1    1    1  

[5 rows x 49 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 49 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    99 non-null     object
 1   Party   99 non-null     object
 2   State   99 non-null     object
 3   B1      99 non-null     int64 
 4   B2      99 non-null     int64 
 5   B3      99 non-null     int64 
 6   B4      99 non-null     int64 
 7   B5      99 non-null     int64 
 8   B6      99 non-null     int64 
 9   B7      99 non-null     int64 
 10  B8      99 non-null     int64 
 11  B9      99 non-null     int64 
 12  B10     99 non-null     int64 
 13  B11     99 non-null     int64 
 14  B12     99 non-null     int64 
 15  B13     99 non-null     int64 
 16  B14     99 non-null     int64 
 17  B15     99 non-null     int64 
 18  B16     99 non-null     int64 
 19  B17     99 non-null     int64 
 20  B18     99 non-null     int64 
 21  B19     99 non-null     int64 
 22  B20     99 non-null     int6

There are 49 columns the first three are the senators Name, party and State and 46 Bills

In [5]:
df['Party'].unique()

array(['D', 'R', 'I'], dtype=object)

There 2 different parties (Democrats, Republicans) and independent 

In [9]:
df['State'].unique()

array(['HI', 'TN', 'CO', 'VA', 'MT', 'IN', 'UT', 'DE', 'NM', 'MO', 'CA',
       'KS', 'KY', 'NC', 'WV', 'WA', 'RI', 'GA', 'NY', 'OK', 'MS', 'MN',
       'ME', 'ND', 'TX', 'ID', 'SC', 'OH', 'CT', 'IL', 'NV', 'WY', 'WI',
       'IA', 'NH', 'NE', 'VT', 'SD', 'MA', 'AZ', 'LA', 'NJ', 'MI', 'AR',
       'FL', 'MD', 'AK', 'PA', 'AL', 'OR'], dtype=object)

In [11]:
def cosine_similarity(u,v):
    dot = np.dot(u,v)
    u_norm = np.linalg.norm(u)
    v_norm = np.linalg.norm(v)
    return dot / (u_norm * v_norm)

def cosine_distance(u,v):
    cosd = 1 - cosine_similarity
    print('the cosine distance', cosd)

There are two distinct functions: one computes cosine similarity, and the other calculates cosine distance

### 1. Find the senator whose voting record is closest to Rhode Island senator, Lincoln Chafee.

In [7]:
RI_senator = df.loc[df['Name'] == 'Chafee','B1':'B46']
RI_senator

B1  B2  B3  B4  B5  B6  B7  B8  B9  B10  ...  B37  B38  B39  B40  B41  \
18   1  -1   1   1   1   1  -1   1   1    1  ...    1   -1   -1    1    1   

    B42  B43  B44  B45  B46  
18    1   -1    1    1   -1  

[1 rows x 46 columns]

Lets take the Rhode island senator Chafee records as the reference 

In [13]:
RI_refrence_senator = df.loc[df['Name'] == 'Chafee','B1':'B46'].to_numpy().flatten()
RI_refrence_senator

array([ 1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  0,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  0,  1,  1,
        0,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1, -1])

In [15]:
def cosine_similarity(u,v):
    dot = np.dot(u,v)
    u_norm = np.linalg.norm(u)
    v_norm = np.linalg.norm(v)
    return dot / (u_norm * v_norm)

def cosine_distance(u,v):
    cosd = 1 - cosine_similarity(u,v)
    return cosd
    

result = []

for i, r in df.iterrows():
    senator_lastname = r['Name']
    comparison_records = r['B1':'B46']

    similarity = cosine_similarity(RI_refrence_senator,comparison_records)
    distance = cosine_distance(RI_refrence_senator,comparison_records)

    result.append({'senator':senator_lastname,'Cosine Similarity':similarity,'Cosine Distance':distance})

result_df = pd.DataFrame(result)
result_df_sorted = result_df.sort_values(by = 'Cosine Similarity',ascending = False )
Closest_senator = result_df_sorted.iloc[1]
print(result_df_sorted)
print("\nSenator who is closest to Chafee:")
print(Closest_senator)


     senator  Cosine Similarity  Cosine Distance
18    Chafee           1.000000    -2.220446e-16
52  Jeffords           0.909326     9.067421e-02
71    Murray           0.841126     1.588736e-01
8   Bingaman           0.818393     1.816068e-01
16  Cantwell           0.786964     2.130359e-01
..       ...                ...              ...
42    Graham           0.382240     6.177603e-01
38      Enzi           0.344850     6.551496e-01
49    Inhofe           0.318264     6.817360e-01
91    Sununu           0.279070     7.209302e-01
21    Coburn           0.272798     7.272023e-01

[99 rows x 3 columns]

Senator who is closest to Chafee:
senator              Jeffords
Cosine Similarity    0.909326
Cosine Distance      0.090674
Name: 52, dtype: object


We take a reference senator as the starting point and traverse through the entire dataset, calculating cosine similarity and distance for each senator. This allows us to identify senators with voting patterns most similar or dissimilar to the reference senator. 

Jefford's voting pattern is most similar to Chafee's, as evidenced by their high cosine similarity. A higher cosine similarity implies a smaller angular difference between their voting vectors.

### 2.Find the senator who disagrees most with Pennsylvania senator, Rick Santorum.

we take pennsylvania senator as the refrence senator

In [19]:
PA_senator = df.loc[df['Name'] == 'Santorum']
PA_senator

Name Party State  B1  B2  B3  B4  B5  B6  B7  ...  B37  B38  B39  B40  \
81  Santorum     R    PA   0   1   1   1   1   1   1  ...    1    1    1    1   

    B41  B42  B43  B44  B45  B46  
81    1    1    1    1    1    1  

[1 rows x 49 columns]

In [13]:
PA_reference_senator = df.loc[df['Name'] == 'Santorum','B1':'B46']
PA_reference_senator = PA_reference_senator.to_numpy().flatten()
PA_reference_senator

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [15]:
def cosine_similarity(u,v):
    dot = np.dot(u,v)
    u_norm = np.linalg.norm(u)
    v_norm = np.linalg.norm(v)
    return dot / (u_norm * v_norm)

def cosine_distance(u,v):
    cosd = 1 - cosine_similarity(u,v)
    return cosd
    
results = []

for i,r in df.iterrows():
    comparison_senator = r['Name']
    comparison_record = r['B1':'B46']

    similarity = cosine_similarity(PA_reference_senator,comparison_record)
    distance = cosine_distance(PA_reference_senator,comparison_record)

    results.append({'Senator':comparison_senator,'Cosine Similarity':similarity,'Cosine Distance':distance})

results_df = pd.DataFrame(results)
results_df_sorted = results_df.sort_values(by = 'Cosine Distance',ascending = False)
most_disagreement = results_df_sorted.loc[results_df_sorted['Cosine Distance'].idxmax()]
print(results_df_sorted)
print("\nSenator who disagrees most with Rick Santorum:")
print(most_disagreement)

     Senator  Cosine Similarity  Cosine Distance
39  Feingold           0.065938     9.340620e-01
76      Reed           0.285732     7.142685e-01
0      Akaka           0.292153     7.078467e-01
60     Leahy           0.292153     7.078467e-01
10     Boxer           0.311111     6.888889e-01
..       ...                ...              ...
92    Talent           0.989071     1.092929e-02
3      Allen           0.989071     1.092929e-02
43  Grassley           0.989071     1.092929e-02
9       Bond           0.989071     1.092929e-02
81  Santorum           1.000000     1.110223e-16

[99 rows x 3 columns]

Senator who disagrees most with Rick Santorum:
Senator              Feingold
Cosine Similarity    0.065938
Cosine Distance      0.934062
Name: 39, dtype: object


By selecting a reference senator and comparing their voting record to every other senator, we can identify those who are most dissimilar, as measured by cosine distance. The senator with the highest cosine distance is the one who disagrees most with the reference senator.

### 3. Compare Jefford's record with each of these 10 senators. Would you classify Jeffords as closer to the Democrats or a Republicans?

In [25]:
Jim_jeffords_record = df.loc[df['Name'] == 'Jeffords','B1':'B46']
Jim_jeffords_record = Jim_jeffords_record.to_numpy().flatten()
Jim_jeffords_record

array([ 1, -1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1,  1,  0,  1, -1,  1,  1, -1])

In [27]:
D_senator = df[df['Party'] == 'D']
R_senator = df[df['Party'] == 'R']

random.seed(42)

D = D_senator.sample(5,random_state=42)
R = R_senator.sample(5,random_state=42)

D_similarities = []
R_similarities = []

for i,r in D.iterrows():
    v_record = r['B1':'B46'].to_numpy()
    similarity = cosine_similarity(Jim_jeffords_record,v_record)
    D_similarities.append(similarity)

for i,r in R.iterrows():
    v_record = r['B1':'B46'].to_numpy()
    similarity = cosine_similarity(Jim_jeffords_record,v_record)
    R_similarities.append(similarity)

avg_D_similarities = np.mean(D_similarities)
avg_R_similarities = np.mean(R_similarities)


print(f'Average similarity to Democrats: {avg_D_similarities}')
print(f'Average similarity to Republicans: {avg_R_similarities}')

if avg_D_similarities > avg_R_similarities:
    print("Jim Jeffords was closer to Democrat")
else:
    print("Jim Jeffords was closer to Republican")
    


Average similarity to Democrats: 0.6117809306785664
Average similarity to Republicans: 0.5472737159884478
Jim Jeffords was closer to Democratic


The average similarities are compared and gives quantitative measure of Jim Jeffords' political alignment by comparing his voting record to a sample of Democratic and Republican senators.