## Extra credit assignment 


I gathere data of Last week Roll Call Votes 118th Congress - 2nd Session (2024)

In [105]:
import pandas as pd
import numpy as np 
import random
df = pd.read_csv('creditdata.csv')
df.head()

Name Party State          B0   B1   B2   B3   B4   B5   B6   B7   B8  \
0     Baldwin     D    WI         Yea  Yea  Yea  Yea  Yea  Yea  Yea  Yea  Yea   
1    Barrasso     R    WY         Nay  Nay  Nay  Nay  Nay  Nay  Nay  Nay  Nay   
2      Bennet     D    CO         Yea  Yea  Yea  Yea  Yea  Yea  Yea  Yea  Yea   
3   Blackburn     R    TN  Not Voting  Nay  Nay  Nay  Nay  Nay  Nay  Nay  Nay   
4  Blumenthal     D    CT         Yea  Yea  Yea  Yea  Yea  Yea  Yea  Yea  Yea   

    B9  B10  
0  Yea  Yea  
1  Nay  Nay  
2  Yea  Yea  
3  Nay  Nay  
4  Yea  Yea

In [107]:
df.info

<bound method DataFrame.info of           Name Party State          B0          B1          B2          B3  \
0      Baldwin     D    WI         Yea         Yea         Yea         Yea   
1     Barrasso     R    WY         Nay         Nay         Nay         Nay   
2       Bennet     D    CO         Yea         Yea         Yea         Yea   
3    Blackburn     R    TN  Not Voting         Nay         Nay         Nay   
4   Blumenthal     D    CT         Yea         Yea         Yea         Yea   
..         ...   ...   ...         ...         ...         ...         ...   
95       Welch     D    VT         Yea         Yea         Yea         Yea   
96  Whitehouse     D    RI         Yea  Not Voting  Not Voting  Not Voting   
97      Wicker     R    MS         Nay         Nay         Nay         Nay   
98       Wyden     D    OR         Yea         Yea         Yea         Yea   
99       Young     R    IN         Nay         Nay         Nay         Nay   

            B4   B5   B6   B7  

In [109]:
columns_to_fill = df.columns[3:13]  


df[columns_to_fill] = df[columns_to_fill].fillna('Abstain')

vote_map = {'Yea': 1, 'Nay': -1, 'Not Voting': 0, 'Abstain': -2}

for col in df.columns[3:14]:
    df[col] = df[col].map(vote_map)

print(df.head())

         Name Party State  B0  B1  B2  B3  B4  B5  B6  B7  B8  B9  B10
0     Baldwin     D    WI   1   1   1   1   1   1   1   1   1   1    1
1    Barrasso     R    WY  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   -1
2      Bennet     D    CO   1   1   1   1   1   1   1   1   1   1    1
3   Blackburn     R    TN   0  -1  -1  -1  -1  -1  -1  -1  -1  -1   -1
4  Blumenthal     D    CT   1   1   1   1   1   1   1   1   1   1    1


In [111]:
df['Party'].unique()

array(['D', 'R', 'I'], dtype=object)

In [113]:
df['State'].unique()

array(['WI', 'WY', 'CO', 'TN', 'CT', 'NJ', 'AR', 'IN', 'AL', 'OH', 'NC',
       'CA', 'WA', 'WV', 'MD', 'DE', 'PA', 'LA', 'ME', 'TX', 'NV', 'ND',
       'ID', 'MT', 'IL', 'IA', 'NE', 'NY', 'SC', 'NH', 'MO', 'NM', 'HI',
       'MS', 'VA', 'AZ', 'MN', 'OK', 'UT', 'MA', 'KS', 'KY', 'OR', 'AK',
       'GA', 'MI', 'RI', 'SD', 'FL', 'VT'], dtype=object)

In [115]:
RI_senator = df.loc[df['Name'] == 'Carper','B0':'B10'].to_numpy().flatten()
RI_senator

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [117]:
def cosine_similarity(u,v):
    dot = np.dot(u, v)
    u_norm = np.linalg.norm(u)
    v_norm = np.linalg.norm(v)


    if u_norm == 0 or v_norm == 0:
        return 0 
    else:
        return dot / (u_norm * v_norm)

def cosine_distance(u,v):
    cosd = 1 - cosine_similarity(u,v)
    return cosd
    

result = []

for i, r in df.iterrows():
    senator_lastname = r['Name']
    comparison_records = r['B0':'B10']

    similarity = cosine_similarity(RI_senator,comparison_records)
    distance = cosine_distance(RI_senator,comparison_records)

    result.append({'senator':senator_lastname,'Cosine Similarity':similarity,'Cosine Distance':distance})

result_df = pd.DataFrame(result)
result_df_sorted = result_df.sort_values(by = 'Cosine Similarity',ascending = False )
Closest_senator = result_df_sorted.iloc[1]
print(result_df_sorted)
print("\nSenator who is closest to Carper:")
print(Closest_senator)

       senator  Cosine Similarity  Cosine Distance
0      Baldwin                1.0              0.0
86      Tester                1.0              0.0
90  Van Hollen                1.0              0.0
32  Gillibrand                1.0              0.0
36      Hassan                1.0              0.0
..         ...                ...              ...
43     Johnson               -1.0              2.0
1     Barrasso               -1.0              2.0
53     Manchin               -1.0              2.0
66        Paul               -1.0              2.0
99       Young               -1.0              2.0

[100 rows x 3 columns]

Senator who is closest to Carper:
senator              Tester
Cosine Similarity       1.0
Cosine Distance         0.0
Name: 86, dtype: object


here i choos senator Blackburn to see who mostly disagree with him

In [119]:
MD_senator = df.loc[df['Name'] == 'Blackburn','B0':'B10'].to_numpy().flatten()
MD_senator

array([ 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [121]:
def cosine_similarity(u,v):
    dot = np.dot(u, v)
    u_norm = np.linalg.norm(u)
    v_norm = np.linalg.norm(v)


    if u_norm == 0 or v_norm == 0:
        return 0 
    else:
        return dot / (u_norm * v_norm)

def cosine_distance(u,v):
    cosd = 1 - cosine_similarity(u,v)
    return cosd
    
results = []

for i,r in df.iterrows():
    comparison_senator = r['Name']
    comparison_record = r['B0':'B10']

    similarity = cosine_similarity(MD_senator,comparison_record)
    distance = cosine_distance(MD_senator,comparison_record)

    results.append({'Senator':comparison_senator,'Cosine Similarity':similarity,'Cosine Distance':distance})

results_df = pd.DataFrame(results)
results_df_sorted = results_df.sort_values(by = 'Cosine Distance',ascending = False)
most_disagreement = results_df_sorted.loc[results_df_sorted['Cosine Distance'].idxmax()]
print(results_df_sorted)
print("\nSenator who disagrees most with Blackburn:")
print(most_disagreement)

      Senator  Cosine Similarity  Cosine Distance
92     Warner          -1.000000     2.000000e+00
41     Hoeven          -1.000000     2.000000e+00
0     Baldwin          -0.953463     1.953463e+00
68       Reed          -0.953463     1.953463e+00
28     Durbin          -0.953463     1.953463e+00
..        ...                ...              ...
60     Mullin           0.953463     4.653741e-02
66       Paul           0.953463     4.653741e-02
57   Menendez           1.000000     2.220446e-16
3   Blackburn           1.000000     2.220446e-16
71     Romney           1.000000     2.220446e-16

[100 rows x 3 columns]

Senator who disagrees most with Blackburn:
Senator              Warner
Cosine Similarity      -1.0
Cosine Distance         2.0
Name: 92, dtype: object


Here i choose senator sinema who is an Independent candidate to classify wheathere is sinema is closer to to the Democrats or a Republicans

In [123]:
s_record = df.loc[df['Name'] == 'Sinema','B0':'B10']
s_record = s_record.to_numpy().flatten()
s_record

array([ 1,  0,  1,  1,  1,  1,  1,  1,  1, -1, -1])

In [125]:

D_senator = df[df['Party'] == 'D']
R_senator = df[df['Party'] == 'R']

random.seed(42)

D = D_senator.sample(5,random_state=42)
R = R_senator.sample(5,random_state=42)

D_similarities = []
R_similarities = []

for i,r in D.iterrows():
    v_record = r['B0':'B10'].to_numpy()
    similarity = cosine_similarity(s_record,v_record)
    D_similarities.append(similarity)

for i,r in R.iterrows():
    v_record = r['B0':'B10'].to_numpy()
    similarity = cosine_similarity(s_record,v_record)
    R_similarities.append(similarity)

avg_D_similarities = np.mean(D_similarities)
avg_R_similarities = np.mean(R_similarities)


print(f'Average similarity to Democrats: {avg_D_similarities}')
print(f'Average similarity to Republicans: {avg_R_similarities}')

if avg_D_similarities > avg_R_similarities:
    print("Sinema was closer to Democrat")
else:
    print("Sinema was closer to Republican")
    


Average similarity to Democrats: 0.5976620428378843
Average similarity to Republicans: -0.31627700713964735
Sinema was closer to Democrat


The average similarities are compared and gives quantitative measure of Sinema' political alignment by comparing her voting record to a sample of Democratic and Republican senators.